# 这是手动触发的基本工作流

name: Manual workflow weather

# 控制操作何时运行。使用UI手动触发时，工作流将运行
# or API.
on:
  workflow_dispatch:
    # 工作流输入的接受
    inputs:
      name:
        # 在UI中显示友好的描述，而不是“名称”
        description: '开始吗？'
        # 如果未明确提供值，则为默认值
        default: '开始！！'
        # 必须提供输入才能运行工作流
        required: true

# 工作流运行由一个或多个可以顺序或并行运行的作业组成

jobs:
  # 此工作流包含一个名为“问候”的作业
  bot:
    # 作业将在其上运行的运行程序类型
    runs-on: ubuntu-latest

    # 步骤表示将作为作业一部分执行的任务序列
    steps:
    # 使用runners shell运行单个命令
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: node ./plugins/caiyun_weather.js
        env:
          bot_api: ${{ secrets.bot_api }}
          caiyun_key: ${{ secrets.caiyun_key }}
          caiyun_gps: ${{ secrets.caiyun_gps }}
